version: 2
jobs:
  first_job:
    working_directory: ~/Activity
    docker:
      - image: ucreateit/php7.2:v0.2
    steps:
      - checkout
      - run:
          name: Print Hello
          command: echo 'Hello'
workflows:
  version: 2
  build_and_test:
    jobs:
      - first_job

